In [2]:
#import the required libraries

import pandas as pd
import numpy as np

In [3]:
#import the raw data

Ctypto_coins = pd.read_csv('crypto_coins.csv')

In [4]:
#print the the data set in order to understand its variables

Ctypto_coins

,Timestamp,Date,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,...,MultiVAC,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti
0,1596326400,02/08/2020,3.801638e+09,NaN,2.068340e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1596412800,03/08/2020,3.765636e+09,NaN,1.959327e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1596499200,04/08/2020,3.943304e+09,NaN,2.034859e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1596585600,05/08/2020,3.965347e+09,NaN,2.085303e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1596672000,06/08/2020,4.144089e+09,NaN,2.136599e+07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,1656547200,30/06/2022,4.609860e+10,5.973266e+09,3.917818e+09,2.673152e+09,2.503643e+09,1.620573e+09,1.129473e+09,8.805920e+08,...,5574.526765,3098.695577,NaN,3191.794734,932.234966,76.008182,76.612045,0.0,0.0,0.0
698,1656633600,01/07/2022,4.598769e+10,5.948651e+09,3.945603e+09,2.677503e+09,2.467068e+09,1.611114e+09,1.131340e+09,8.630599e+08,...,5412.415585,3113.140250,NaN,3185.642841,919.542532,73.382771,72.077378,0.0,0.0,0.0
699,1656720000,02/07/2022,4.571368e+10,5.976332e+09,3.904847e+09,2.637227e+09,2.416282e+09,1.601541e+09,1.118539e+09,8.697622e+08,...,5923.457447,3154.038705,2876.914532,1492.374165,928.383171,70.884189,72.402693,0.0,0.0,0.0
700,1656806400,03/07/2022,4.591318e+10,5.961448e+09,4.769674e+09,2.623568e+09,2.515649e+09,1.557003e+09,1.116408e+09,8.664804e+08,...,5908.150347,3063.665444,2891.131379,1445.776783,915.949652,72.338655,71.628747,0.0,0.0,0.0
701,1656892800,04/07/2022,4.579631e+10,5.955433e+09,4.817103e+09,2.652975e+09,2.466390e+09,1.521098e+09,1.114876e+09,8.618863e+08,...,5596.161193,3005.148559,2896.335944,1446.218068,910.900692,70.830638,75.600183,0.0,0.0,0.0

In [6]:
#Count the number of variables & observations

print('No. of observations & No. of variables:', Ctypto_coins.shape)

No. of observations & No. of variables: (702, 128)

In [7]:
#Count the number of Null values

Ctypto_coins.isna().sum()

Timestamp       0
Date            0
Ethereum        0
BSC            90
Tron            0
             ...
SXnetwork     684
Bittorrent    558
Ultra         409
zkSync        462
Coti          648
Length: 128, dtype: int64

In [8]:
#Check the Dtype

Ctypto_coins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Columns: 128 entries, Timestamp to Coti
dtypes: float64(126), int64(1), object(1)
memory usage: 702.1+ KB

In [15]:
#Drop the "Timestamp" variable as it's irrelevant

Ctypto_coins.drop(['Timestamp'], axis = 1, inplace = True)

In [9]:
#Replace the NaN values with 0

Ctypto_coins = Ctypto_coins.fillna(0)

In [17]:
Ctypto_coins

,Date,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,Fantom,...,MultiVAC,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti
0,02/08/2020,3.801638e+09,0.000000e+00,2.068340e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,03/08/2020,3.765636e+09,0.000000e+00,1.959327e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,04/08/2020,3.943304e+09,0.000000e+00,2.034859e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,05/08/2020,3.965347e+09,0.000000e+00,2.085303e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
4,06/08/2020,4.144089e+09,0.000000e+00,2.136599e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,30/06/2022,4.609860e+10,5.973266e+09,3.917818e+09,2.673152e+09,2.503643e+09,1.620573e+09,1.129473e+09,8.805920e+08,9.326138e+08,...,5574.526765,3098.695577,0.000000,3191.794734,932.234966,76.008182,76.612045,0.0,0.0,0.0
698,01/07/2022,4.598769e+10,5.948651e+09,3.945603e+09,2.677503e+09,2.467068e+09,1.611114e+09,1.131340e+09,8.630599e+08,8.658352e+08,...,5412.415585,3113.140250,0.000000,3185.642841,919.542532,73.382771,72.077378,0.0,0.0,0.0
699,02/07/2022,4.571368e+10,5.976332e+09,3.904847e+09,2.637227e+09,2.416282e+09,1.601541e+09,1.118539e+09,8.697622e+08,8.492853e+08,...,5923.457447,3154.038705,2876.914532,1492.374165,928.383171,70.884189,72.402693,0.0,0.0,0.0
700,03/07/2022,4.591318e+10,5.961448e+09,4.769674e+09,2.623568e+09,2.515649e+09,1.557003e+09,1.116408e+09,8.664804e+08,8.432540e+08,...,5908.150347,3063.665444,2891.131379,1445.776783,915.949652,72.338655,71.628747,0.0,0.0,0.0
701,04/07/2022,4.579631e+10,5.955433e+09,4.817103e+09,2.652975e+09,2.466390e+09,1.521098e+09,1.114876e+09,8.618863e+08,8.457496e+08,...,5596.161193,3005.148559,2896.335944,1446.218068,910.900692,70.830638,75.600183,0.0,0.0,0.0

In [21]:
# I wanted the drop the date column just for a while till I round all the columns then int64 

new_df = Ctypto_coins.iloc[:, 1:127]

In [22]:
new_df

,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,Fantom,Arbitrum,...,MultiVAC,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti
0,3.801638e+09,0.000000e+00,2.068340e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,3.765636e+09,0.000000e+00,1.959327e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,3.943304e+09,0.000000e+00,2.034859e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,3.965347e+09,0.000000e+00,2.085303e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
4,4.144089e+09,0.000000e+00,2.136599e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,4.609860e+10,5.973266e+09,3.917818e+09,2.673152e+09,2.503643e+09,1.620573e+09,1.129473e+09,8.805920e+08,9.326138e+08,7.425182e+08,...,5574.526765,3098.695577,0.000000,3191.794734,932.234966,76.008182,76.612045,0.0,0.0,0.0
698,4.598769e+10,5.948651e+09,3.945603e+09,2.677503e+09,2.467068e+09,1.611114e+09,1.131340e+09,8.630599e+08,8.658352e+08,7.403210e+08,...,5412.415585,3113.140250,0.000000,3185.642841,919.542532,73.382771,72.077378,0.0,0.0,0.0
699,4.571368e+10,5.976332e+09,3.904847e+09,2.637227e+09,2.416282e+09,1.601541e+09,1.118539e+09,8.697622e+08,8.492853e+08,7.349294e+08,...,5923.457447,3154.038705,2876.914532,1492.374165,928.383171,70.884189,72.402693,0.0,0.0,0.0
700,4.591318e+10,5.961448e+09,4.769674e+09,2.623568e+09,2.515649e+09,1.557003e+09,1.116408e+09,8.664804e+08,8.432540e+08,7.379814e+08,...,5908.150347,3063.665444,2891.131379,1445.776783,915.949652,72.338655,71.628747,0.0,0.0,0.0
701,4.579631e+10,5.955433e+09,4.817103e+09,2.652975e+09,2.466390e+09,1.521098e+09,1.114876e+09,8.618863e+08,8.457496e+08,6.181968e+08,...,5596.161193,3005.148559,2896.335944,1446.218068,910.900692,70.830638,75.600183,0.0,0.0,0.0

In [23]:
new_df = round(new_df).astype(int)

In [24]:
new_df

,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,Fantom,Arbitrum,...,MultiVAC,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti
0,3801638378,0,20683397,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3765635710,0,19593266,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3943304030,0,20348594,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3965347237,0,20853031,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4144089179,0,21365989,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,46098601724,5973266036,3917818257,2673152218,2503642898,1620572603,1129473306,880592001,932613803,742518233,...,5575,3099,0,3192,932,76,77,0,0,0
698,45987690981,5948651151,3945602713,2677503381,2467068195,1611113725,1131340058,863059857,865835229,740321017,...,5412,3113,0,3186,920,73,72,0,0,0
699,45713680961,5976332223,3904846646,2637226654,2416282492,1601541245,1118539263,869762205,849285252,734929397,...,5923,3154,2877,1492,928,71,72,0,0,0
700,45913179055,5961448417,4769673919,2623568289,2515648673,1557003461,1116407508,866480366,843253951,737981356,...,5908,3064,2891,1446,916,72,72,0,0,0
701,45796309998,5955432856,4817103144,2652975231,2466390313,1521098061,1114876106,861886279,845749622,618196803,...,5596,3005,2896,1446,911,71,76,0,0,0

In [25]:
#Concat the date variable back to the data frame

new_df['Date'] = Ctypto_coins['Date']

In [26]:
new_df

,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,Fantom,Arbitrum,...,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti,Date
0,3801638378,0,20683397,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,02/08/2020
1,3765635710,0,19593266,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,03/08/2020
2,3943304030,0,20348594,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,04/08/2020
3,3965347237,0,20853031,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,05/08/2020
4,4144089179,0,21365989,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,06/08/2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,46098601724,5973266036,3917818257,2673152218,2503642898,1620572603,1129473306,880592001,932613803,742518233,...,3099,0,3192,932,76,77,0,0,0,30/06/2022
698,45987690981,5948651151,3945602713,2677503381,2467068195,1611113725,1131340058,863059857,865835229,740321017,...,3113,0,3186,920,73,72,0,0,0,01/07/2022
699,45713680961,5976332223,3904846646,2637226654,2416282492,1601541245,1118539263,869762205,849285252,734929397,...,3154,2877,1492,928,71,72,0,0,0,02/07/2022
700,45913179055,5961448417,4769673919,2623568289,2515648673,1557003461,1116407508,866480366,843253951,737981356,...,3064,2891,1446,916,72,72,0,0,0,03/07/2022
701,45796309998,5955432856,4817103144,2652975231,2466390313,1521098061,1114876106,861886279,845749622,618196803,...,3005,2896,1446,911,71,76,0,0,0,04/07/2022

In [27]:
#Make the date variable to be Date

new_df['Date'] = pd.to_datetime(new_df['Date']).dt.date

In [29]:
new_df

,Ethereum,BSC,Tron,Avalanche,Solana,Polygon,Cronos,Waves,Fantom,Arbitrum,...,Zilliqa,Kusama,Palm,Ravencoin,SXnetwork,Bittorrent,Ultra,zkSync,Coti,Date
0,3801638378,0,20683397,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020-02-08
1,3765635710,0,19593266,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020-03-08
2,3943304030,0,20348594,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020-04-08
3,3965347237,0,20853031,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020-05-08
4,4144089179,0,21365989,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020-06-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,46098601724,5973266036,3917818257,2673152218,2503642898,1620572603,1129473306,880592001,932613803,742518233,...,3099,0,3192,932,76,77,0,0,0,2022-06-30
698,45987690981,5948651151,3945602713,2677503381,2467068195,1611113725,1131340058,863059857,865835229,740321017,...,3113,0,3186,920,73,72,0,0,0,2022-01-07
699,45713680961,5976332223,3904846646,2637226654,2416282492,1601541245,1118539263,869762205,849285252,734929397,...,3154,2877,1492,928,71,72,0,0,0,2022-02-07
700,45913179055,5961448417,4769673919,2623568289,2515648673,1557003461,1116407508,866480366,843253951,737981356,...,3064,2891,1446,916,72,72,0,0,0,2022-03-07
701,45796309998,5955432856,4817103144,2652975231,2466390313,1521098061,1114876106,861886279,845749622,618196803,...,3005,2896,1446,911,71,76,0,0,0,2022-04-07

In [30]:
#Convert the DataFrame into csv file

new_df.to_csv('Different_coins.csv', index = False)

# References:

    - https://note.nkmk.me/en/python-pandas-t-transpose/
    
    - https://thispointer.com/drop-first-row-of-pandas-dataframe-3-ways/
    
    - https://www.delftstack.com/howto/python-pandas/split-column-in-python-pandas/#:~:text=We%20can%20use%20the%20pandas,to%20the%20entire%20Dataframe%20column.
    
    - https://www.statology.org/pandas-select-multiple-columns/